### ISSUE TITLE
new version upgrade failed

### ISSUE THREAD

**Issue by Dave2048** [dr01d3r/redcap-em-orca-search#6] opened 2018-07-06 15:04 UTC
Here's the error message:

Subject: REDCap External Module Hook Exception - orca_search

[This message was automatically generated by REDCap]

The 'orca_search' module threw the following exception when calling the hook method 'redcap_every_page_top':

Exception: You must supply the following either as a GET parameter or as the last argument to this method: pid in C:\inetpub\wwwroot\redcap\redcap_v8.2.2\ExternalModules\classes\AbstractExternalModule.php:653
Stack trace:
#0 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\ExternalModules\classes\AbstractExternalModule.php(635): ExternalModules\AbstractExternalModule->requireParameter('pid', NULL)
#1 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\ExternalModules\classes\AbstractExternalModule.php(221): ExternalModules\AbstractExternalModule->requireProjectId(NULL)
#2 C:\inetpub\wwwroot\redcap\modules\orca_search_v1.2.2\OrcaSearch.php(34): ExternalModules\AbstractExternalModule->getProjectSetting('replace_add_edi...')
#3 [internal function]: ORCA\OrcaSearch\OrcaSearch->redcap_every_page_top(NULL)
#4 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\ExternalModules\classes\ExternalModules.php(1180): call_user_func_array(Array, Array)
#5 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\ExternalModules\classes\ExternalModules.php(1240): ExternalModules\ExternalModules::startHook('orca_search', 'v1.2.2', Array)
#6 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\Classes\Hooks.php(37): ExternalModules\ExternalModules::callHook('every_page_top', Array)
#7 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\Classes\HtmlPage.php(185): Hooks::call('redcap_every_pa...', Array)
#8 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\ControlCenter\header.php(26): HtmlPage->PrintHeader()
#9 C:\inetpub\wwwroot\redcap\redcap_v8.2.2\ExternalModules\manager\control_center.php(4): require_once('C:\\inetpub\\wwwr...')
#10 {main}

URL: https://xxx.xxxx.edu/redcap/redcap_v8.2.2/ExternalModules/manager/control_center.php
Server: xxx.xxxx.edu
Module Name: Orca Search Module (orca_search)
Module Author(s): xxxx

After that, i receive the following when try to access the upgrade page again:
500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed.

**Comment by dr01d3r** [comment] 2018-07-06 18:06
@Dave2048 This error looks related to an issue with PHP 7.1 or higher.  Have you recently upgraded PHP?  If not, can you make sure the modules folder can be written to?

**Comment by Dave2048** [comment] 2018-07-06 19:01
@dr01d3r PHP Version 7.1.18
we were able to recover by switching the active version back to the previous version (1.1.0)

**Comment by dr01d3r** [comment] 2018-07-07 15:16
@Dave2048 I was able to determine that the issue is not PHP related.  There was a bug in EM core code in REDCap 8.2.2 that was allowing EM hook functions to execute outside of project context; however; once in a project's context, it will only execute the functions on projects where the module is enabled.

I will patch this by accounting for the missing $project_id and not allowing the rest of the function to execute.  Initial tests against v8.2.2 are looking good so far.

**Comment by Dave2048** [comment] 2018-07-09 13:49
@dr01d3r  thanks for the quick fix!

**Comment by dr01d3r** [comment] 2018-07-11 03:20
This has been resolved in release v1.2.3

**Closed by dr01d3r** 2018-07-11 03:20 UTC
